BOARD = GENERIC_RP_RP2040
BOOTLOADER = rp2040

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
WS2812_DRIVER = vendor
BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
AUDIO_SUPPORTED = no

MOUSEKEY_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c

ANALOG_DRIVER_REQUIRED = yes

RGBLIGHT_SUPPORTED = yes
RGBLIGHT_ENABLE = yes

RGB_MATRIX_SUPPORTED = no
RGB_MATRIX_ENABLE = no
RGB_MATRIX_DRIVER = WS2812

SRC += analog.c